### ISSUE TITLE
Asynchronous requests

### ISSUE THREAD

**Issue by anthonyprintup** [OALabs/hashdb-ida#12]
When performing requests the UI (especially with large IAT scans) the UI is frozen and IDA is unusable while the requests are performed.
To fix this we should use `asyncio`'s `Futures`.

[Example](https://docs.python.org/3/library/asyncio-future.html) combined with [add_done_callback](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.add_done_callback):
![image](https://user-images.githubusercontent.com/92564080/137989659-8464cd46-c50b-4793-be97-43d873189c07.png)
![image](https://user-images.githubusercontent.com/92564080/137989836-9c5500bc-75fb-4011-85d3-ea62d4a28238.png)

More elegant alternatives would include the use of async libraries such as:
- [aiohttp](https://docs.aiohttp.org/en/stable/),
- [requests-futures](https://pypi.org/project/requests-futures/),
- [grequests](https://pypi.org/project/grequests/), and others.

**Comment by herrcore** [comment]
I'm curious how this would work with IDA... specifically if it locks the python command line?

**Comment by herrcore** [comment]
Yasss! This is pretty exciting : ))

Also, I'll kill the py 2.7 feature request for now... python 3 is the future I guess. Unless we hear a lot of screaming, long live Python 3.
