### ISSUE TITLE
HashDB Lookup kills IDA on M1 macs

### ISSUE THREAD

**Issue by Lichtlos** [OALabs/hashdb-ida#14]
**Tested versions:**
main branch at `4d73263cffac975e1e47e67eb7fb55bfb85416a2`
and release version 1.4.0

**IDA Version:**
Version 7.6.210427 macOS arm64

**Python:** 
3.9.7

**Steps to reproduce:**

1. Load malshare sample (from OALabs YT Video)
https://malshare.com/sample.php?action=detail&hash=132fa71af952927e1961f735e68ae38a3305e7ae8d7197c170d071f74db60d1c

2. Right click on hash 992892395 in sub_4010D7 
Select "HashDB Lookup"

Result: IDA crashes with "Oops! internal error 40217 occurred.
<img width="480" alt="Screenshot 2021-10-23 at 16 08 50" src="https://user-images.githubusercontent.com/581311/138560140-e1ca0d1d-417a-46b0-ac3d-6a7de25cec49.png">
<img width="1004" alt="Screenshot 2021-10-23 at 16 08 43" src="https://user-images.githubusercontent.com/581311/138560142-98a05894-28b7-44f0-baf3-5ad7a08c2170.png">
"

**Comment by n0thing2speak** [comment]
![image](https://user-images.githubusercontent.com/19668794/144360405-9839428a-7698-458c-b548-62349c92c071.png)
same

**Comment by Lichtlos** [comment]
FYI Hex-rays has a fix for this and will provide you with fixed ida_kernwin for python2 and python3. Just contact support@hex-rays.com
