### ISSUE TITLE
Unable to create enum of strings with special characters

### ISSUE THREAD

**Issue by Demonslay335** [OALabs/hashdb-ida#17]
An enum member is not populated properly when the resulting string has a special character - only tested with a preceding `-` (e.g. `-path`), unsure if position matters or if other characters cause the issue. Assuming it is IDA rejecting the string as a valid enum member name.

Sample (BlackMatter v2):
https://www.virustotal.com/gui/file/520bd9ed608c668810971dbd51184c6a29819674280b018dc4027bc38fc42e57

Function `0x411464` contains hashes for command line parameter strings that reproduce the issue. The algorithm is `add_ror13`. The hashes are correctly identified by HashDB, but the string is *not* added to the `hashdb_strings` enum.

![image](https://user-images.githubusercontent.com/5551512/139113291-128ea1f6-7506-4757-999b-872eb1462756.png)

**Comment by anthonyprintup** [comment]
Once PR #18 gets merged I'll look into creating a sanitizer that'll generate qualified names out of strings.

**Comment by anthonyprintup** [comment]
So, I'm not exactly sure what's allowed in the C standard, but here's an initial idea of how we can fix this: https://regex101.com/r/wc9ALK/1/

Of course, we'd have to implement a sanitizer which properly transforms the string:
- if a name starts with `0-9` -> append an `_` to it?
- replace bad characters with `_`?

Another idea would be to ask the user to manually set the string?

**Comment by anthonyprintup** [comment]
Turns out IDA defines a specific character set of allowed characters:
![image](https://user-images.githubusercontent.com/92564080/140426029-65bc42d0-3b4c-4bda-b9de-76c5e7712d28.png)

The solution is to ask the user to provide the name any time an unqualified name is encountered.

**Comment by anthonyprintup** [comment]
API to check the names with: [ida_name.is_ident_cp](https://hex-rays.com/products/ida/support/idapython_docs/ida_name.html#ida_name.is_ident_cp)

**Comment by herrcore** [comment]
Just a test: https://github.com/OALabs/hashdb-ida/blob/2ea6ba745c094f3b5baeee50e0b11bdfb8e4b4f6/hashdb.py#L10
