### ISSUE TITLE
Error invalid hash selected

### ISSUE THREAD

**Issue by herrcore** [OALabs/hashdb-ida#44]
sample: [041a05dd902a55029449bf412cedbe59a593f8d4e67d4ae37cf7a928c92f22ca](https://malshare.com/sample.php?action=detail&hash=041a05dd902a55029449bf412cedbe59a593f8d4e67d4ae37cf7a928c92f22ca)

offset: 0x20c0 (0x402ec0)

Replicate behaviour.
- convert data into DWORD (hex representation)
- select any hash algorithm 
- right-click DWORD -> HashDb Lookup

**Error invalid hash selected**

**Comment by anthonyprintup** [comment]
After a bit of debugging, here's what I found out;

When double-clicking a value (effectively attempting to select it - the UI highlights the entire value!) `ida_kernwin.get_highlight` no longer functions properly (it'll return a value up until where the caret was, or return the last partially selected value).

# Selecting a value by clicking on it once:
![image](https://user-images.githubusercontent.com/92564080/187099714-45866a92-8c50-4bbc-a26a-2a2db0a63f7c.png)

# Selecting a value by double-clicking it:
![image](https://user-images.githubusercontent.com/92564080/187099741-43efb152-bab2-4d93-9e1f-a699176a1ccc.png)

# Improperly selecting a value (multiple selection):
![image](https://user-images.githubusercontent.com/92564080/187099757-f8f7f43a-59fc-47dd-bc25-322a0a2b1b6d.png)

Possible solutions:
- if `ida_kernwin.get_highlight` returns a zero value as the flags, we're dealing with a partial selection (double-clicked value): warn the user about this, and
- if both `ida_kernwin.get_highlight` and `ida_kernwin.read_range_selection` (this is what `idc.read_selection_(start/end)` use under the hood) return proper values: warn the user that they're attempting to highlight multiple values.

I'll submit a PR when I have time.
